apiVersion: v2
name: openshift-console
description: A Helm chart for Kubernetes

type: application

# This is the chart version.
version: 1.0.1

# This is the version number of the application being deployed.
appVersion: "4.16.0" # https://access.redhat.com/support/policy/updates/openshift # paragraph "OpenShift Support Matrix"
